version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:postgres}
      POSTGRES_DB: ${POSTGRES_DB:forte_assets}
    ports:
      - "${POSTGRES_PORT:5432}:5432"
    volumes:
      - forte_db:/var/lib/postgresql/data

volumes:
  forte_db:
